# Site settings
author: pullopen
title: Mastodon搭建指南
SEOTitle: 技术小白搭建Mastodon站点指南
header-img: universe.jpg
post-img: universe2.png
email: admin@pullopen.xyz
description: ""
keyword: "Mastodon, Fediverse"
url: "https://pullopen.github.io"              # your host, for absolute URL
baseurl: "/"  
imgurl: "/assets/img"
# baseurl: ""                             # 本地调试使用
# imgurl: "/assets/img"


# Basic settings
sass: 
  sass_dir: _scss
  # style: compressed


# SNS settings
RSS: true
#weibo_username:     kasmine
# zhihu_username:     kasmine
github_username:    pullopen
#twitter_username:  kasmine
#facebook_username:  kasmineLiao
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
paginate: 8
exclude: ["less", "node_modules", "Gruntfile.js",
  "package.json",
  "README.md",
  "README.zh.md"]
anchorjs: true                          # 如何设置



# Gems -> Rename to plugins
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate, jekyll-feed]


markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings  待完善
#disqus_username: _your_disqus_short_name_



# Analytics settings
# Google Analytics
# ga_track_id: 'UA-89922034-1'            # Format: UA-xxxxxx-xx
# ga_domain:



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "没有任何IT背景的技术小白要如何搭建一个Mastodon实例？这里给你提供详细指南！"
sidebar-avatar: /assets/img/fediverse.png      # use absolute URL, seeing it's used in both `/` and `/about/`


# Progressive Web Apps
chrome-tab-theme-color: "lightred"
service-worker: true


# Catalog settings
catalog: true

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Tags
tags: [{

}]



# Friends
friends: [{
        title: "长毛象（Mastodon）社区搭建详解",
        href: "https://guide.mastodon.im"
    },{
      title: "奇想齋",
      href: "https://i.nebula.moe/"
    },{
      title: "影子屋",
      href: "https://blog.bgme.me/"
    }
]

# 推荐top书籍
#topbook: {
#  name: "JavaScript高级程序设计（第3版）",
#  author: "[美] Nicholas C·Zakas ",
#  star: "★★★★★ 9.3   1360人评价",
#  introduction: "全书从JavaScript 语言实现的各个组成部分——语言核心、DOM、BOM、事件模型讲起，深入浅出地探讨了面向对象编程、Ajax 与Comet 服务器端通信，HTML5 表单、媒体、Canvas（包括WebGL）及Web Workers、地理定位、跨文档传递消息、客户端存储（包括IndexedDB）等新API，还介绍了离线应用和与维护、性能、部署相关的最佳开发实践。本书附录展望了未来的API 和ECMAScript Harmony 规范。"
#}

# To use Gittalk comments  https://github.com/gitalk/gitalk#Usage
# jekyll synatx: https://jekyllrb.com/docs/liquid/
gittalk:
  # Note: A GitHub Application is needed for authorization, if you don't have one, going to https://github.com/settings/applications/new register a new one.
  # You must specify the website domain url in the Authorization callback URL field.
  clientID: f449c28cc7aa6f14a5d5 # 改成你的 GitHub Application Client ID
  clientSecret: 70f56a6387a1183216801d1b14c6ae75fdf0f93f  # 改成你的 GitHub Application Client Secret,
  repository: pullopen.github.io  # 改成你的 Storage gittalk's repository
  owner: pullopen  # 改成你的 GitHub repo owner,
  admin: pullopen  # 改成你的 GitHub repo owner and collaborators, only these guys can initialize github issues eg. 'colynn,daattali'

#Show related posts based on categories
related-posts:
  active: true
  title: "相关文章"

tagson:
  active: true

feed:
  excerpt_only: true




